In [3]:
import numpy as np
arr = np.array([11,22,33,44,55,66,77,88,99])
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(len(arr))

<class 'numpy.ndarray'>
1
(9,)
9


In [7]:
print(arr[0])
print(arr[0:3])
print(arr[::-1])

11
[11 22 33]
[99 88 77 66 55 44 33 22 11]


In [10]:
a1 = np.arange(0,10,1)
a2 = np.arange(10)
print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
